tmgmt_local.settings:
  type: config_object
  label: 'Tmgmt local settings'
  mapping:
    use_admin_theme:
      type: boolean
      label: 'Use admin theme'

tmgmt.translator.settings.local:
  type: tmgmt.translator_base
  label: 'Drupal user settings'
  mapping:
    allow_all:
      type: boolean
      label: 'Allow all'

action.configuration.tmgmt_local_task_assign_multiple:
  type: action_configuration_default
  label: 'Assign multiple task configuration'

action.configuration.tmgmt_local_task_assign_to_me:
  type: action_configuration_default
  label: 'Assign task to me configuration'

action.configuration.tmgmt_local_task_unassign_multiple:
  type: action_configuration_default
  label: 'Assign task to me configuration'
